//tinyredis_util.util,tests.tinyredis_util.util
//Automatically generated by unit_threaded.gen_ut_main, do not edit by hand.
import unit_threaded;

int main(string[] args)
{
    return args.runTests!(
                          "tinyredis_util.util",
                          "tests.tinyredis_util.util"
                          );
}
